version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: priv_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: privcelebrations
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./privcelebrations
    container_name: priv_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/privcelebrations
      PORT: 3000
      NODE_ENV: production
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./client
    container_name: priv_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
