[build]
  base    = "privcelebrations"
  command = "npm run build"
  publish = "dist/public"

[context.development.environment]
  NODE_VERSION = "18"

[context.production.environment]
  # Add VITE_API_URL in Netlify UI or here (but don't commit secrets). Example placeholder:
  VITE_API_URL = "https://privcelebrations-backend.onrender.com"

[[redirects]]
  from = "/api/*"
  to = "https://privcelebrations-backend.onrender.com/api/:splat"
  status = 200
  force = true
